# Generated by Django 3.2.2 on 2022-01-09 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quadros', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=128, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quadro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='quadros.quadro')),
            ],
            options={
                'verbose_name_plural': 'Tipos',
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=128, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quadro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='quadros.quadro')),
            ],
            options={
                'verbose_name_plural': 'Status',
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='Linha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=128, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quadro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='quadros.quadro')),
            ],
            options={
                'verbose_name_plural': 'Linhas',
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='Epico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=128, unique=True)),
                ('descricao', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quadro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='quadros.quadro')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='quadros.status')),
            ],
            options={
                'verbose_name_plural': 'Epicos',
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='Coluna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=128, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quadro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='quadros.quadro')),
            ],
            options={
                'verbose_name_plural': 'Colunas',
                'ordering': ('created_at',),
            },
        ),
    ]
