# Generated by Django 3.2.2 on 2022-01-09 17:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quadros', '0002_coluna_epico_linha_status_tipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Atividade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=128)),
                ('descricao', models.TextField(blank=True)),
                ('data_de_inicio', models.DateTimeField(auto_now_add=True)),
                ('data_de_entrega', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('coluna', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='quadros.coluna')),
                ('epico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='quadros.epico')),
                ('linha', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='quadros.linha')),
                ('membros', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='quadros.status')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='quadros.tipo')),
            ],
            options={
                'verbose_name_plural': 'Atividades',
                'ordering': ('created_at',),
            },
        ),
    ]
