from django.urls import path

from . import views

app_name = 'projetos'

urlpatterns = [
    path('', views.index, name='index'),
    path('inicio/', views.inicio, name='inicio'),
    path('listas_de_projetos/', views.listas_de_projetos,
         name='listas_de_projetos'),
    path('editar_projeto/<int:id>',
         views.editar_projeto, name='editar_projeto'),
    path('deletar_projeto/<int:id>',
         views.deletar_projeto, name='deletar_projeto'),
    path('detalhes_do_projeto/<int:id_projeto>/',
         views.detalhes_do_projeto,
         name='detalhes_do_projeto'),
    path('lista_de_listas_do_projeto/<int:id>',
         views.lista_de_listas_do_projeto, name='lista_de_listas_do_projeto'),
    path('editar_lista_do_projeto/<int:id>',
         views.editar_lista_do_projeto, name='editar_lista_do_projeto'),
    path('detalhes_da_lista_do_projeto/<int:id>',
         views.detalhes_da_lista_do_projeto, name='detalhes_da_lista_do_projeto'),
    path('deletar_lista_do_projeto/<int:id_lista>/<int:id_projeto>',
         views.deletar_lista_do_projeto, name='deleta_lista_do_projeto'),
    path('nova_atividade_do_projeto/<int:id_lista>/<int:prox>', views.nova_atividade_do_projeto,
         name='nova_atividade_do_projeto'),
    path('detalhes_da_atividade_do_projeto/<int:id>',
         views.detalhes_da_atividade_do_projeto, name='detalhes_da_atividade_do_projeto'),
    path('lista_de_atividades_do_projeto/<int:id>',
         views.lista_de_atividades_do_projeto, name='lista_de_atividades_do_projeto'),
    path('editar_atividade_do_projeto/<int:id>',
         views.editar_atividade_do_projeto, name='editar_atividade_do_projeto'),
    path('mudar_estado_da_atividade_do_projeto/<int:id>/<int:dir>',
         views.mudar_estado_da_atividades_do_projeto, name='mudar_estado_da_atividade_do_projeto'),
    path('deletar_atividade_do_projeto/<int:id>',
         views.deletar_atividade_do_projeto, name='deletar_atividade_do_projeto'),
    path('nova_subatividade_do_projeto/<int:id_atividade>', views.nova_subatividade_do_projeto,
         name='nova_subatividade_do_projeto'),
    path('editar_subatividade_do_projeto/<int:id>',
         views.editar_subatividade_do_projeto, name='editar_subatividade_do_projeto'),
    path('mudar_estado_da_subatividade_do_projeto/<int:id>/<int:dir>',
         views.mudar_estado_da_subatividades_do_projeto, name='mudar_estado_da_subatividade_do_projeto'),
    path('deletar_subatividade_do_projeto/<int:id>',
         views.deletar_subatividade_do_projeto, name='deletar_subatividade_do_projeto'),
]
