# Generated by Django 3.2.2 on 2021-06-24 22:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projetos', '0003_projeto_descricao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atividade',
            name='responsavel',
        ),
        migrations.AddField(
            model_name='atividade',
            name='descricao',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='atividade',
            name='membros',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='atividade',
            name='requisitos',
            field=models.ManyToManyField(to='projetos.Atividade'),
        ),
        migrations.AlterField(
            model_name='atividade',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('fazendo', 'Fazendo'), ('feito', 'Feito')], max_length=10),
        ),
    ]
