# Generated by Django 3.2.2 on 2021-06-24 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0004_auto_20210624_1959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atividade',
            name='requisitos',
            field=models.ManyToManyField(blank=True, to='projetos.Atividade'),
        ),
    ]
