# Generated by Django 3.2.2 on 2021-07-16 14:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projetos', '0006_auto_20210711_1438'),
    ]

    operations = [
        migrations.AddField(
            model_name='lista',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('fazendo', 'Fazendo'), ('feito', 'Feito')], default='pendente', max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='atividade',
            name='membros',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
