# Generated by Django 3.2.2 on 2021-07-17 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0007_auto_20210716_1151'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='lista',
            constraint=models.UniqueConstraint(fields=('nome', 'projeto'), name='projetos_lista_unique'),
        ),
    ]
