# Generated by Django 3.2.2 on 2021-07-17 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0008_lista_projetos_lista_unique'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='lista',
            name='projetos_lista_unique',
        ),
        migrations.AddConstraint(
            model_name='lista',
            constraint=models.UniqueConstraint(fields=('projeto', 'nome'), name='unico'),
        ),
    ]
