# Generated by Django 3.2.2 on 2021-07-17 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0009_auto_20210716_2138'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='lista',
            name='unico',
        ),
        migrations.AlterField(
            model_name='atividade',
            name='titulo',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='lista',
            name='nome',
            field=models.CharField(max_length=128),
        ),
        migrations.AddConstraint(
            model_name='atividade',
            constraint=models.UniqueConstraint(fields=('titulo', 'lista'), name='unica_atv'),
        ),
        migrations.AddConstraint(
            model_name='lista',
            constraint=models.UniqueConstraint(fields=('projeto', 'nome'), name='unica_lista'),
        ),
    ]
