# Generated by Django 3.2.2 on 2021-10-10 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0012_itens'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Itens',
            new_name='SubAtividade',
        ),
    ]
