# Generated by Django 3.2.2 on 2021-10-11 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0013_rename_itens_subatividade'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='subatividade',
            constraint=models.UniqueConstraint(fields=('titulo', 'atividade'), name='unica_subatv'),
        ),
    ]
