# Generated by Django 3.2.2 on 2021-11-05 00:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0014_subatividade_unica_subatv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atividade',
            name='requisitos',
            field=models.ManyToManyField(blank=True, limit_choices_to={'lista': True}, related_name='_projetos_atividade_requisitos_+', to='projetos.Atividade'),
        ),
        migrations.AlterField(
            model_name='subatividade',
            name='atividade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projetos.subatividade'),
        ),
    ]
