# Generated by Django 3.2.2 on 2021-11-05 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0015_auto_20211104_2111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atividade',
            name='requisitos',
            field=models.ManyToManyField(blank=True, related_name='_projetos_atividade_requisitos_+', to='projetos.Atividade'),
        ),
    ]
