# Generated by Django 3.2.2 on 2021-11-05 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0016_alter_atividade_requisitos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atividade',
            name='requisitos',
            field=models.ManyToManyField(blank=True, limit_choices_to={'lista': True}, related_name='_projetos_atividade_requisitos_+', to='projetos.Atividade'),
        ),
    ]
