# Generated by Django 3.2.2 on 2021-11-05 00:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0017_alter_atividade_requisitos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subatividade',
            name='atividade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projetos.atividade'),
        ),
    ]
